EionRobb/purple-mattermost

README.md
Hi Eion, 
Thanks for starting this! 
Proposing some early text for a README file--just a thought, totally open to however you'd like to document. 
Really excited about this integration and enabling new use cases for the Pidgin and Mattermost communities,
=> README update?

INSTALL.md, README.md, VERIFICATION.md
Work-in-progress, I'm going to install this weekend and write-up a bit of user's guide
=> Update README, add install guide, verification guide

INSTALL.md, README.md, VERIFICATION.md
Ready for review and merge
- Updating feature list 
- Document installer, adding screens below
=> Adding .exe instructions, new features

INSTALL.md, Makefile, purple-mattermost.spec
Adding rpm / srpm build to Makefile, plus instructions in INSTALL
=> Adding rpm target to Makefile

libmattermost.c
simple user information display implementation.
=> Adding Get Info / Info 

libmattermost.c
In our environment I can find accounts where no first_name last_name or nickname are defined and account name is a cryptic unique character string (that's due to gitlab auth using Microsoft ADFS SSO where users can register 'lightweight' accounts using only e-mail address ..).
Proposed patch: 
- displays email in buddy search results
- proposes alias in buddy add from search results (in order: nickname -> first_name last_name -> email)
=> Add email to buddy search results, propose alias for buddy add

libmattermost.c
Tested with libpurple2, please check with libpurple3 too .... (I think this part of API did not change ..)
=> Adding tooltips to Mattermost buddies

libmattermost.c
minor fix: missing error message on Buddy Add for non-existing MM user.
=> Add buddy error 

libmattermost.c
Sorry, stupid error ... resulted in mm_save_user_prefs not working()  (json_generator_to_data() returns empty - {} data while used with wrong node type..)
=> Json array to string fix

README.md, libmattermost.c
=> Emojione info

libmattermost.c
- displays in Room List additional fields: channel header and channel purpose
- prevents adding direct channels to Room List
- adds account menu shortcut
- adds joined / more channels labels to categories in Room List
=> Roomlist beautifications

INSTALL.md, README.md
Adding some info to docs about new features - please feel free to correct (not a native speaker ;-)) I think adding "Room List..." and "Search for Users..." screenshots to INSTALL.md would be nice (I'm using it on linux so my screenshot would look rather different than yours).
=> channel sync: docs update

libmattermost.c
Makes libpurple present file name rather than (unreadable) MM public file URL.
=> present file name rather than url

libmattermost.c
This should address https://github.com/EionRobb/purple-mattermost/issues/11
Also sets msg time to create_time if update_time is 0 to avoid pidgin displaying beginning of the epoch
as msg timestamp.
=> Mark bot messages as such in conv.

libmattermost.c
Coming back with the other part of https://github.com/EionRobb/purple-mattermost/pull/51/
While highlight plugin could possibly highlight some keywords this PR highlights (well, uses underline since not used by MM plus bold for 'personal' mentions) mention words as setup in MM user preferences - so I think functionality is complementary.
(this PR comes after https://github.com/EionRobb/purple-mattermost/pull/54)
Example:
=> add mention words to chat messages

libmattermost.c
This PR adds (slack) attachment handling
- should address https://github.com/EionRobb/purple-mattermost/issues/12
- I think we do best we can with limited xhtml-im libpurple capabilities ...
Not handled:
- multiple colums in attachments (just displayed in single column)
- symbolic color names ("green", "warning" .. etc)
Please check with libpurple-3 (the util.c libpurple xhtml-im handler is really fragile .. easy to get non-htmlized output even while using a sequence of valid html tags ...)
And this is how it looks like:
=> (Slack) Attachments handling

libmattermost.c
What this PR does:
- sets initial status on pidgin startup / account enable 
- sets offline status on pidgin exit / account disable
- adds 'invisible' status ( sets status on MM to offline, but
stays connected (status stays offline until next change)
Status changes take between 30 to 60 seconds on our MM with > 600 
users.
When being 'invisible' and posting status changes briefly to online then
back (should be possible to be more 'invisible': while using official client
posting does not change offline status ? ...)
=> set my status on MM server

INSTALL.md, Makefile, libmattermost.c
- adapts Makefile to build on MacOSX
- adds mkdio.h check
- fixes code for macosx gcc.
- adds INSTALL.md macosx section.
=> macosx build

Makefile, README.md, glibcompat.h, libmattermost.c, purple2compat/glibcompat.h, purple2compat/http.c, purple2compat/http.h, purple2compat/image-store.h, purple2compat/image.h, purple2compat/internal.h, purple2compat/plugins.h, purple2compat/purple-socket.c, purple2compat/purple-socket.h, purplecompat.h
Hi @EionRobb , this is not production ready, needs some further fixing and reviewing .. but perhaps you would have some time to have a look at it in next weeks  ? (while I'm away from keyboard)
=> W.I.P.: Porting plugin to V4 API

libmattermost.c
We weren't resetting cookies properly.
This addresses issue #78
=> Fix login problem

AUTHORS, Makefile, README.md, glibcompat.h, libmattermost-helpers.c, libmattermost-helpers.h, libmattermost-json.c, libmattermost-json.h, libmattermost-markdown.c, libmattermost-markdown.h, libmattermost.c, libmattermost.h, purplecompat.c, purplecompat.h
OK, so now the V4 merge is done: let's split code into multiple files ?
This is first attempt, no code / functionality changes, only few missing _() added.
=> Splitting code into multiple files

AUTHORS, Makefile, README.md, glibcompat.h, libmattermost-helpers.c, libmattermost-helpers.h, libmattermost-json.c, libmattermost-json.h, libmattermost-markdown.c, libmattermost-markdown.h, libmattermost.c, libmattermost.h, purplecompat.c, purplecompat.h
sorry. messed up master with my not-so-well remembered git commands ... so merging this one again.
=> Code split - again

libmattermost-helpers.c, libmattermost-helpers.h, libmattermost.c, libmattermost.h
Adds 'Server Info' dialog
Enables/Disables slash commands / public file links depending on server config.
=> Adding /client/config handling.

libmattermost-helpers.c, libmattermost-helpers.h, libmattermost.c, libmattermost.h
Reads available slash commands from server using  /commands?team_id= API call,
provides commands help (Accounts -> Mattermost Account -> Slash Commands),
executes commands and reports errors.
=> slash commands processing and help

INSTALL.md
individial coookies are not shown anymore in preference. better to use the "inspect element" function.
=> MMAUTHTOKEN

libmattermost.c
The xfer->fd was always set to -1 which caused some binary rubbish to be sent. I've changed to to proper file reading based on the xfer->local_filename and it works for me nicely.
=> fixed file reading during send

libmattermost.c
I've tested muting reactions only for private chat. This patch makes it work for group chats as well.
=> Do not open empty window on reaction to group chat

libmattermost.c
Fixed memleak discussed in #108
=> Fixed memleak in mm_get_channel_approximate_view_time

libmattermost.c
This fixes an issue with server returning 401 response code with "Invalid or expired session, please login again" message.
=> Add "X-Requested-With: XMLHttpRequest" HTTP request header

libmattermost.c
This should fix the issue, but it should be thoroughly checked. I'm not sure what other places the problem with @username might be affecting.
=> Fixes issue #118
