- INSTALL.md
`build-essentials` doesn't exist, it's `build-essential`
> error in package name

- purple-mattermost.spec
RPM spec file for packaging on RHEL/Fedora/CentOS distributions (following the packaging of other purple plugins in EPEL)
> RPM spec file for RHEL/CentOS/Fedora distributions

- INSTALL.md
- README.md
- libmattermost.c
While this does not really solve #13 , at least it provides a (temporary) workaround allowing to connect to mattermost instances where only gitlab authentication is enabled.
Please consider merging until a proper solution of obtaining MMAUTHTOKEN via the plugin is found.
> (temporary) workaround for GitLab (MMAUTHTOKEN) authentication

- libmattermost.c
Just few questions/comments about this:
1) mm_add_channels_to_blist could be probably simplified  after merging this ? 
2) should mm_get_users_by_ids also populate  ma->one_to_ones/ma->one_to_ones_rev ?
2)  buddies handling - I believe that this should be integrated with server actions:
add buddy -> should add buddy locally and a direct channel on server
remove buddy -> should remove buddy locally and remove direct channel on server 
(and then local buddy list possibly should be re-synced from server and changes applied 
locally ? in case user uses other clients in parallel)
Your opinion ?
Cheers
Jarek
> Populate pidgin Mattermost group with buddies from server.

- libmattermost.c
Adds simple 'Email Buddy' context action - on linux requires xdg-open, should work on windows too (but I have not checked: just seen similar code in use somewhere)
> Email Buddy action

- libmattermost.c
Keeps purple buddies and channels in sync with MM server / other MM clients running in parallel. 
I guess that invoking mm_add_channels_to_blist() periodically would be useful ? - for now this synchronization happens only on startup ?
> channel list / buddy list synchronization with MM server

- libmattermost.c
example (even if that one does not make too much sense ;-)):
```/cmd shortcuts```
this PR allows 'chatting' with BOTs, and makes plugin not discard ephemeral msg type.
> Add MM slash command pass-through and ephemeral response handling

- libmattermost.c
Adds Auto-Join account option - new channels are automatically opened. off by default.
For now this happens only on startup: but can be added for other cases if you merge this one and https://github.com/EionRobb/purple-mattermost/pull/38
> Auto-Join new chats account option

- README.md
- libmattermost.c
While clicking 'Join' in 'Room List' client tried to get channel info from a channel user is not subscribed to: that failed. This PR adds calling MM '/join' command before other operations. 
Side effect / benefit: on startup join command will be executed for all rooms subscribed to. (MM will just ignore join if channel already joined).
> Join room fix

- libmattermost.c
Now we have a way of displaying both channel header and purpose (https://github.com/EionRobb/purple-mattermost/pull/43) it would be nice to have commands to set these from plugin too.
> commands to set channel header or purpose

- libmattermost.c
This fixes / adds the following:
- Buddies/Conversation > New Instant Message to existing (or not) buddies.
- Conversation -> IM (from people list).
- Search for Users > Search results > IM.
- Creates new conversation for an incoming message from not-yet-buddy.
also:
- adds system_admin role display
- gets more information in Get Info  / Info and updates the info for existing buddy
Cheers
Jarek
> fixing sending im msg to non-yet-buddies

- libmattermost.c
This PR shall fix multi-team handling (that I broke with my channel_sync PR ..). Everyrthing seems to work as far as I can tell except:
- while being invited to new chat we do not see messages until pidgin restart (line 2529) - not sure this worked before ?
- while starting with no blist.xml and disabling/enabling account i get crash (line 1432) .. which looks like my libpurple may be the problem (restarting pidgin and enabling/disabling account even multiple times where blist.xml is there does not cause the crash ...?)
- other problems solved:
-  trying to message a bot (or oneself) shows error message and notes in in conv. window. (so no more 'looping' we've seen after last patches), not added as buddy.
- own account back on people list in chat rooms (I think that follows more other …
> Multi team

- libmattermost.c
So, here is what it does:
- gets, stores and displays more information about users in get info / tooltip
- adds about myself account menu option
- makes auto generated aliases an option. (since we use usernames for mentions , having buddies displayed as aliases may not be what we want ..)
- adds display of channel 'operators' (MM channel founders) in people lists.
... and of course there is some code reshuffling supporting above changes.
(shared code moved to functions, login process more streamlined for password and gitlab token login, etc ...)
(this is followup to: https://github.com/EionRobb/purple-mattermost/pull/51, reaction to mentions and maybe highlighting mention words will come later: these need this PR code)
Please review, Thanks !
Jarek
PS: yeah, I know you asked for separate …
> more info about ourselves, other users, channel ops (plus mentions handling)

- libmattermost.c
Renders in pidgin chats following markdown:
- headings
- blockquotes
- code blocks
- lines
- strike
not implemented: tables
Provided as account option enabled by default (can imagine some people may want to use pidgin to avoid markdown rendering ...)
Note: to be checked on libpurple3
Jarek
and here is a rendering comparison between firefox and pidgin 2.10:
> render more markdown in purple

- INSTALL.md
I had issues compiling because my OS' locale is fr_FR, which caused a problem when RPM tried to check de %changelog field.
> Added locale management in RPM build steps

- libmattermost.c
when client was joining channels where we are added when it is running, display_name was not set properly, resulting in inability to open conv. window or conv. window opening with an empty title. This P{R fixes it.
> FIx missing display_name for channels

- libmattermost.c
I'm using new chat window for every conversation in pidgin. It is annoying to have empty windows pop-up on me just because someone added a +1 to a recent post. Since emojis are not shown by pidgin anyway, I propose to ignore these updates.
> Do not pop up window on reactions to posts, such as emojis

- libmattermost.c
When deleted messages are shown (usually when read from history), mark them as deleted
> Mark deleted messaged in conversation

- libmattermost.c
When somebody adds emojis to a post, we do not need to see that after logging in from the client. This patch removes updates and leaves only new posts, edits and deletes.
> Do not show reactions while loading history

- libmattermost-helpers.c
- libmattermost.c
- libmattermost.h
When public links are disabled on a server, there is just an error message `[error: public links disabled on server, cannot get file: test.txt]`. I've added a permalink to the post containing the file so that it can be easily accessed in this case. Please check whether this is the right way to create the url, I'm not sure how the team_id really works for individual chats.
> show link to post when file links are disabled

- Makefile
Default of `install` is `-m755`, which is wrong for icons: it should be
`-m644`.
> Fix icon permissions on installation

- libmattermost.c
When there is no uri on mmfile set one. It works pretty well in my environment where we have server without public links. It presents the direct link onto the file which is more comfortable than opening the whole web client I think.
> set mmfile uri if not set

- .github/workflows/release.yml
- libmattermost.c
- libmattermost.h
**Features:**
- Fetch the last 60 messages when a channel is joined for the first time.
Steps to test:
- Join a new channel from Pidgin and the joined channel room will automatically open and fetch the last 60 messages(if exists)
- When another user adds a Pidgin(Mattermost user using Pidgin) user to a channel on Mattermost then that channel room will automatically open and fetch the last 60 messages(if exists)
**Bug fixes/Improvements**
- When a Pidgin(Mattermost user using Pidgin) user was added to a channel on Mattermost by another user then that channel was visible in the Pidgin rooms list but the user was not able to open that channel room on Pidgin until restarting it, now it is fixed and the user doesn't need to restart the Pidgin app to open a newly added channel/room.
> [Feature]: Fetch last 60 messages when a channel is joined for the first time from Pidgin.
